# Generated by Django 4.2.8 on 2023-12-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stops_no', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('distance', models.IntegerField()),
                ('halt', models.IntegerField()),
                ('bus_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='route.busstation')),
            ],
        ),
        migrations.CreateModel(
            name='BusRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('Arrival', models.TimeField()),
                ('Departure', models.TimeField()),
                ('bus_stops', models.ManyToManyField(to='route.busstop')),
            ],
        ),
    ]
