# Generated by Django 4.2.8 on 2023-12-27 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busstation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
