# Generated by Django 4.2.8 on 2023-12-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('arrival_time', models.TimeField()),
                ('departure_time', models.TimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bus.bus')),
                ('trip_route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='route.busroute')),
            ],
        ),
    ]
