# Generated by Django 4.2.8 on 2023-12-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bus', '0001_initial'),
        ('route', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_end', to='route.busstop')),
                ('bus_seat', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='bus.busseat')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_start', to='route.busstop')),
            ],
        ),
    ]
