# Generated by Django 4.2.8 on 2023-12-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0009_alter_bus_capacity'),
        ('schedule', '0002_schedule_end_date_schedule_published_and_more'),
        ('ticket_reservation', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='trip',
            new_name='schedule',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('schedule', 'date', 'bus_seat')},
        ),
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Pending', max_length=20),
        ),
    ]
