# Generated by Django 4.2.8 on 2023-12-27 05:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('route', '0002_alter_busstation_name'),
        ('bus', '0009_alter_bus_capacity'),
        ('schedule', '0003_alter_schedule_end_date_alter_schedule_start_date'),
        ('ticket_reservation', '0005_reservation_bus_seat_reservation_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Canceled', 'Canceled'), ('Ongoing', 'Ongoing'), ('Done', 'Done')], default='Pending', max_length=20)),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_edit', models.DateTimeField(auto_now=True)),
                ('arrival_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_end', to='route.busstop')),
                ('bus_seat', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='bus.busseat')),
                ('departure_stop', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='reservation_start', to='route.busstop')),
                ('passenger', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'date', 'bus_seat')},
            },
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
