# Generated by Django 4.2.8 on 2023-12-06 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('number_plate', models.CharField(max_length=200)),
                ('have_ac', models.BooleanField(default=False)),
                ('sleeping_coach', models.BooleanField(default=False)),
                ('double_decker', models.BooleanField(default=False)),
                ('capacity', models.IntegerField(editable=False)),
                ('no_of_column', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusSeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row', models.CharField(editable=False, max_length=1)),
                ('column', models.IntegerField(editable=False)),
                ('bus', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='bus.bus')),
            ],
            options={
                'unique_together': {('bus', 'row', 'column')},
            },
        ),
    ]
