# Generated by Django 4.2.8 on 2023-12-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0002_alter_bus_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='no_of_column',
            field=models.IntegerField(editable=False),
        ),
    ]
