# Generated by Django 4.2.8 on 2023-12-07 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_alter_bus_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busseat',
            name='bus',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.bus'),
        ),
        migrations.AlterField(
            model_name='busseat',
            name='column',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='busseat',
            name='row',
            field=models.CharField(),
        ),
    ]
