# Generated by Django 4.2.8 on 2023-12-07 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_alter_bus_capacity_alter_busseat_bus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.BooleanField(),
        ),
    ]
